[project]
name = "email-refiner-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cloudpickle>=3.1.2",
    "google-adk[eval]>=1.26.0",
    "google-cloud-aiplatform[adk,agent-engines]>=1.139.0",
    "google-genai>=1.65.0",
    "litellm>=1.82.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
    "sseclient-py>=1.9.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]
